#!/bin/bash

while getopts ":lakn:" opt; do
    case ${opt} in
        a )
            adname=$OPTARG
            echo "$adname" >> $SPOTIKILL_PATH/blocklist.txt
            exit 0
            ;;
        l )
            cat "$SPOTIKILL_PATH/blocklist.txt"
            exit 0
            ;;
        k )
            if ps aux | grep spotikill; then
                pkill -f spotikill.sh
            fi
            exit 0
            ;;
        n )
            nohup spotikill.sh &
            exit 0
            ;;
        \? )
            echo "Invalid Option: -$OPTARG" 1>&2
            exit 1
            ;;
    esac
    shift $((OPTIND -1))
done
