#!/bin/bash

while getopts ":la:kd:" opt; do
    case ${opt} in
        a )
            adname=$OPTARG
            echo "$adname" >> $SPOTIKILL_PATH/blocklist.txt
            ;;
        l )
            cat "$SPOTIKILL_PATH/blocklist.txt"
            ;;
        k )
            if ps aux | grep spotikill; then
                pkill -f spotikill.sh
            fi
            ;;
        d )
            file=$SPOTIKILL_PATH/blocklist.txt
            awk "!/$OPTARG/" $file > temp && mv temp $file
            ;;
        \? )
            echo "Invalid Option: -$OPTARG" 1>&2
            exit 1
            ;;
    esac
done

shift $((OPTIND -1))
