#!/bin/bash

if [ ! -f $SPOTIKILL_PATH/track.log ]; then
    cd $SPOTIKILL_PATH
    touch track.log
fi

LOGPATH=$SPOTIKILL_PATH/track.log

echo "$(date): Initiated spotikill" >> $LOGPATH

while [ true ];
do

    trap "echo $(date): Terminated spotikill >> $LOGPATH" EXIT

    if ps aux | grep spotify;
    then

        osascript <<EOT

            set masterpath to system attribute "SPOTIKILL_PATH"
            set lpt to ""&masterpath&"/track.log"

            if application "Spotify" is running then

                tell application "Spotify"

                    set c to the current track
                    set tS to round ((duration of c / 1000) mod 60) rounding down

                    set bfPath to ""&masterpath&"/blocklist.txt"
                    set lns to paragraphs of (read POSIX file bfPath)

                    set blocklist to {}

                    repeat with ln in lns
                        copy ln to the end of blocklist 
                    end repeat

                    if blocklist contains name of c and ts <= 30 then

                        do shell script "echo $(date): Detected advertisement>> "&lpt&""

                        tell application "Spotify" to quit
                        delay 2
                        tell application "Spotify" to activate
                        delay 2
                        tell application "System Events" to set visible of application process "Spotify" to false

                        tell application "Spotify" to play
                        
                        do shell script "echo $(date): Skipped advertisement>> "&lpt&""
                        do shell script "echo $(date): Current track is "&name of current track&">> "&lpt&""
                    
                    end if

                end tell

            end if

EOT
    fi

    if [[ $(wc -l <$LOGPATH) -ge 100 ]]
    then
        > $LOGPATH
    fi

    sleep 2
done