#!/bin/bash

if [ ! -f $SPOTIKILL_PATH/track.log ]; then
    cd $SPOTIKILL_PATH
    touch track.log
fi

LOGPATH=$SPOTIKILL_PATH/track.log

echo "$(date): Initiated spotikill" >> $LOGPATH

while [ true ];
do

    trap "echo $(date): Terminated spotikill >> $LOGPATH" EXIT

    if ps aux | grep spotify;
    then

        osascript - "$LOGPATH" <<EOT

            on run argv
            set lpt to item 1 of argv as text

            if application "Spotify" is running then

                tell application "Spotify"

                    set c to the current track
                    set tS to round ((duration of c / 1000) mod 60) rounding down

                    set bool to tS <= 30 and name of c is "Advertisement"

                    if tS <= 30 and name of c is "Advertisement" then
                        tell application "Spotify" to quit
                        delay 2
                        tell application "Spotify" to activate
                        delay 1
                        tell application "System Events" to set visible of application process "Spotify" to false

                        tell application "Spotify"
                            next track
                            play
                        end tell

                        do shell script "echo $(date): Skipped advertisement>> "&lpt&""
                        do shell script "echo $(date): Current track is "&name of current track&">> "&lpt&""

                    end if

                end tell

            end if

            end run

EOT
    fi

    if [[ $(wc -l <$LOGPATH) -ge 100 ]]
    then
        > $LOGPATH
    fi

    sleep 2
done